In [493]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

from sklearn.decomposition import PCA

In [ ]:
df = pd.read_csv('dataset/cleaned_data/properties_post_feature_selection_v2.csv')

In [495]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [496]:
df['furnishing_type'].value_counts()

furnishing_type
0.0    2349
1.0    1018
2.0     187
Name: count, dtype: int64

In [497]:
# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished
df['furnishing_type'] = df['furnishing_type'].replace({0.0:'unfurnished',1.0:'semifurnished',2.0:'furnished'})

In [498]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor

In [499]:
X = df.drop(columns=['price'])
y = df['price']

In [500]:
# Applying the log1p transformation to the target variable
y_transformed = np.log1p(y)

## 1. Ordinal Encoding

In [501]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

In [502]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode)
    ], 
    remainder='passthrough'
)

In [503]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [504]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [505]:
scores.mean(),scores.std()

(np.float64(0.7363096633436828), np.float64(0.03238005754429936))

In [506]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [507]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [508]:
y_pred = pipeline.predict(X_test)

In [509]:
y_pred = np.expm1(y_pred)

In [510]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.9463822160089356

my model is going mistake around 94 lac

In [511]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [512]:

model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [513]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [514]:
model_output

[['linear_reg', np.float64(0.7363096633436828), 0.9463822160089356],
 ['svr', np.float64(0.7642012011196355), 0.8472636473483922],
 ['ridge', np.float64(0.7363125343993554), 0.9463387741853386],
 ['LASSO', np.float64(0.05943378064493574), 1.528905986892753],
 ['decision tree', np.float64(0.7791441231752287), 0.7325348786852341],
 ['random forest', np.float64(0.8812076754507299), 0.52549837891874],
 ['extra trees', np.float64(0.8677831975547573), 0.5455178973728204],
 ['gradient boosting', np.float64(0.8725466748471172), 0.5763696394563058],
 ['adaboost', np.float64(0.7511779562022487), 0.8378491932551121],
 ['mlp', np.float64(0.8059416581736653), 0.7086198071767977],
 ['xgboost', np.float64(0.8894876835260124), 0.5040475141482346]]

In [515]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [516]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.889488  0.504048
5       random forest  0.881208  0.525498
6         extra trees  0.867783  0.545518
7   gradient boosting  0.872547  0.576370
9                 mlp  0.805942  0.708620
4       decision tree  0.779144  0.732535
8            adaboost  0.751178  0.837849
1                 svr  0.764201  0.847264
2               ridge  0.736313  0.946339
0          linear_reg  0.736310  0.946382
3               LASSO  0.059434  1.528906

## 2. OneHotEncoding

In [517]:
ordinal_cols = [col for col in columns_to_encode 
                if col not in ['sector','agePossession','furnishing_type']]
onehot_cols = ['sector','agePossession','furnishing_type']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), ordinal_cols),
        ('cat1',OneHotEncoder(drop='first'), onehot_cols)
    ], 
    remainder='passthrough'
)

In [518]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [519]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [520]:
scores.mean()

np.float64(0.8546157852681182)

In [521]:
scores.std()

np.float64(0.015992396207243933)

In [522]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [523]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'balcony',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first'),
                                                  ['sector', 'agePossession',
                                                   'furnishing_type'])])),
                ('regressor', LinearRegression())])

In [524]:
y_pred = pipeline.predict(X_test)

In [525]:
y_pred = np.expm1(y_pred)

In [526]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.6496721144190014

In [527]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [528]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [529]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [530]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [531]:
model_df.sort_values(['mae'])

                 name        r2       mae
6         extra trees  0.886546  0.480563
10            xgboost  0.883654  0.499824
9                 mlp  0.875769  0.504640
5       random forest  0.870979  0.530116
1                 svr  0.882774  0.533683
7   gradient boosting  0.856399  0.601304
4       decision tree  0.791243  0.626036
0          linear_reg  0.854616  0.649672
2               ridge  0.854922  0.653719
8            adaboost  0.725035  0.896386
3               LASSO -0.003598  1.576392

### 3. OneHotEncoding With PCA

In [532]:
ordinal_cols = [col for col in columns_to_encode 
                if col not in ['sector','agePossession','furnishing_type']]
onehot_cols = ['sector','agePossession','furnishing_type']


# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), ordinal_cols),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False), onehot_cols)
    ], 
    remainder='passthrough'
)

In [533]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('pca', PCA(n_components=0.95)),
    ('regressor', LinearRegression())
])

In [534]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [535]:
scores.mean()

np.float64(0.7644414727636656)

In [536]:
scores.std()

np.float64(0.028840370479173715)

In [537]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('pca', PCA(n_components=0.95)),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [538]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [539]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

c:\Users\hassa\Downloads\Data\Hassan\Learning\ML Courses\Course-DS Bootcamp-KN\venv312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [540]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [541]:
model_df.sort_values(['mae'])

                 name        r2       mae
6         extra trees  0.840165  0.592239
10            xgboost  0.820537  0.613982
5       random forest  0.820397  0.638596
1                 svr  0.823530  0.664194
7   gradient boosting  0.824066  0.695369
9                 mlp  0.822687  0.724182
4       decision tree  0.618672  0.805353
0          linear_reg  0.764441  0.906183
2               ridge  0.764486  0.906239
8            adaboost  0.689426  0.935064
3               LASSO -0.003598  1.576392

### 4. Target Encoder

In [ ]:
!pip install category_encoders

In [542]:
import category_encoders as ce

columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']
ordinal_cols = [col for col in columns_to_encode 
                if col not in ['sector','agePossession', 'furnishing_type']]
# onehot_cols = ['sector','agePossession','furnishing_type']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), ordinal_cols),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession', 'furnishing_type']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [544]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [545]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [546]:
scores.mean(),scores.std()

(np.float64(0.8289766283709458), np.float64(0.018936274205272753))

In [547]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [548]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [549]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [550]:
model_output

[['linear_reg', np.float64(0.8289766283709458), 0.7127278833922406],
 ['svr', np.float64(0.8630431690346227), 0.5844485164747009],
 ['ridge', np.float64(0.8289922969248622), 0.7132458877809231],
 ['LASSO', np.float64(-0.003597657277664901), 1.576391507281618],
 ['decision tree', np.float64(0.8139241525623986), 0.5769174927386749],
 ['random forest', np.float64(0.8943142238829285), 0.4706025377272561],
 ['extra trees', np.float64(0.8938398942790606), 0.4748650169646663],
 ['gradient boosting', np.float64(0.883504381311958), 0.5264883921832506],
 ['adaboost', np.float64(0.8142808748928736), 0.6942960136271378],
 ['mlp', np.float64(0.8546787909510833), 0.5922610269218748],
 ['xgboost', np.float64(0.8963924924369696), 0.47547857824340983]]

In [551]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [552]:
model_df.sort_values(['mae'])

                 name        r2       mae
5       random forest  0.894314  0.470603
6         extra trees  0.893840  0.474865
10            xgboost  0.896392  0.475479
7   gradient boosting  0.883504  0.526488
4       decision tree  0.813924  0.576917
1                 svr  0.863043  0.584449
9                 mlp  0.854679  0.592261
8            adaboost  0.814281  0.694296
0          linear_reg  0.828977  0.712728
2               ridge  0.828992  0.713246
3               LASSO -0.003598  1.576392

### 5. Hyperparameter Tuning on XGBRegressor with GridSearchCV

In [553]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = {
    'regressor__n_estimators': [50, 100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__max_samples':[0.1, 0.25, 0.5, 1.0],
    'regressor__max_features': [None, 'sqrt']
}

param_grid_xgb = {
    'regressor__learning_rate': [0.1, 0.01],
    'regressor__max_depth': [5, 8, 12, 20, 30],
    'regressor__n_estimators': [100, 200, 300],
    'regressor__colsample_bytree': [0.3, 0.4, 0.5, 0.8, 1]
}

param_grid_rf = {
    'regressor__n_estimators': [100, 200, 300, 500],      
    'regressor__max_depth': [None, 10, 20, 30],    
    'regressor__min_samples_split': [2, 5, 10],   
    'regressor__min_samples_leaf': [1, 2, 4],     
    'regressor__max_features': ['sqrt', 'log2', None]
}

param_grid_et = {
    'regressor__n_estimators': [100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__min_samples_split': [2, 5, 10],
    'regressor__min_samples_leaf': [1, 2, 4],
    'regressor__max_features': ['sqrt', 'log2', None],
    'regressor__bootstrap': [False, True]  # extra trees can also use bootstrap
}

# param_grid = {
#     'regressor__learning_rate': [0.01, 0.03, 0.05, 0.1, 0.2],
#     'regressor__max_depth': [3, 5, 8, 12, 20, 30],
#     'regressor__n_estimators': [100, 200, 300, 500, 800],
#     'regressor__colsample_bytree': [0.3, 0.4, 0.5, 0.7, 0.8, 1.0],
#     'regressor__subsample': [0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
#     'regressor__gamma': [0, 0.1, 0.5, 1, 2, 5],
#     'regressor__min_child_weight': [1, 2, 4, 6, 8, 10],
#     'regressor__reg_alpha': [0, 0.1, 0.5, 1, 2, 5],   # L1 regularization
#     'regressor__reg_lambda': [0, 0.1, 0.5, 1, 2, 5],  # L2 regularization
#     'regressor__max_bin': [256, 300, 400, 512],       # if using histogram tree method
#     'regressor__scale_pos_weight': [1, 3, 5]          # useful if target is skewed
# }

In [555]:
columns_to_encode = ['property_type', 'balcony', 'furnishing_type', 'luxury_category', 'floor_category']
# columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [ ]:
pipeline_xgb = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor())
])

kfold = KFold(n_splits=10, shuffle=True, random_state=42)
search_xgb = GridSearchCV(pipeline_xgb, param_grid_xgb, cv=kfold, scoring='r2', n_jobs=-1, verbose=4)

In [577]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
search_xgb.fit(X_train,y_train)

y_pred_xgb = search_xgb.predict(X_test)
y_pred_xgb = np.expm1(y_pred_xgb)
mean_absolute_error(np.expm1(y_test),y_pred_xgb)

Fitting 10 folds for each of 150 candidates, totalling 1500 fits

0.47066952360665576

In [578]:
search_xgb.best_score_

np.float64(0.8953634094452262)

In [594]:
search_xgb.best_params_

{'regressor__colsample_bytree': 0.8,
 'regressor__learning_rate': 0.1,
 'regressor__max_depth': 5,
 'regressor__n_estimators': 300}

In [595]:
search_xgb.best_estimator_

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'balcony',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['agePosse...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.1,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=5, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=None,
                              num_parallel_tree=None, ...))])

### 6. Hyperparameter Tuning on RandomForestRegressor with GridSearchCV

In [581]:
pipeline_rf = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor())
])

kfold = KFold(n_splits=10, shuffle=True, random_state=42)
search_rf = GridSearchCV(pipeline_rf, param_grid_rf, cv=kfold, scoring='r2', n_jobs=-1, verbose=4)

In [582]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
search_rf.fit(X_train,y_train)

y_pred = search_rf.predict(X_test)
y_pred = np.expm1(y_pred)
mean_absolute_error(np.expm1(y_test),y_pred)

Fitting 10 folds for each of 432 candidates, totalling 4320 fits

0.47431484502972227

In [583]:
search_rf.best_score_

np.float64(0.8831196450986261)

### 7 .Hyperparameter Tuning on ExtraTreesRegressor with GridSearchCV

In [562]:
pipeline_etr = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', ExtraTreesRegressor())
])

kfold = KFold(n_splits=10, shuffle=True, random_state=42)
search_etr = GridSearchCV(pipeline_etr, param_grid_rf, cv=kfold, scoring='r2', n_jobs=-1, verbose=4)

In [563]:
# X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
# search_etr.fit(X_train,y_train)

# y_pred = search_etr.predict(X_test)
# y_pred = np.expm1(y_pred)
# mean_absolute_error(np.expm1(y_test),y_pred)

In [564]:
# search_etr.best_score_

### 8. Hyperparameter Tuning on XGBRegressor with optuna

In [604]:
from xgboost import XGBRegressor
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder
import category_encoders as ce
import optuna

columns_to_encode = ['property_type', 'balcony', 'furnishing_type', 'luxury_category', 'floor_category']

# ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1', OneHotEncoder(drop='first', sparse_output=False), ['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ],
    remainder='passthrough'
)


def objective(trial):
    # Suggest hyperparameters for XGB
    n_estimators = trial.suggest_int('n_estimators', 100, 500)
    max_depth = trial.suggest_int('max_depth', 3, 30)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.2)
    subsample = trial.suggest_float('subsample', 0.5, 1.0)
    colsample_bytree = trial.suggest_float('colsample_bytree', 0.3, 1.0)
    gamma = trial.suggest_float('gamma', 0, 5)
    min_child_weight = trial.suggest_int('min_child_weight', 1, 10)
    reg_alpha = trial.suggest_float('reg_alpha', 0, 5)  # L1 regularization
    reg_lambda = trial.suggest_float('reg_lambda', 0, 5)  # L2 regularization
    max_bin = trial.suggest_int('max_bin', 256, 512)  # only if using histogram tree method
    scale_pos_weight = trial.suggest_int('scale_pos_weight', 1, 5)

    # Pipeline with preprocessor and XGBRegressor
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', XGBRegressor(
            n_estimators=n_estimators,
            max_depth=max_depth,
            learning_rate=learning_rate,
            subsample=subsample,
            colsample_bytree=colsample_bytree,
            gamma=gamma,
            min_child_weight=min_child_weight,
            reg_alpha=reg_alpha,
            reg_lambda=reg_lambda,
            max_bin=max_bin,
            random_state=42,
            objective='reg:squarederror',
            tree_method='hist'  # required if using max_bin
        ))
    ])
    
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    score = cross_val_score(pipeline, X_train, y_train, cv=kfold, scoring='r2').mean()
    
    return score

In [605]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=200)

[I 2026-02-28 22:10:29,996] A new study created in memory with name: no-name-fecdae0f-d092-4416-9d59-1a2135eaa811
[I 2026-02-28 22:10:30,933] Trial 0 finished with value: 0.8483623591561059 and parameters: {'n_estimators': 163, 'max_depth': 19, 'learning_rate': 0.08067343770149185, 'subsample': 0.745795621699881, 'colsample_bytree': 0.9287321582186456, 'gamma': 1.620918256130797, 'min_child_weight': 3, 'reg_alpha': 4.968927040541196, 'reg_lambda': 2.9110531254904943, 'max_bin': 397, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.8483623591561059.
[I 2026-02-28 22:10:31,860] Trial 1 finished with value: 0.8373499238964657 and parameters: {'n_estimators': 261, 'max_depth': 21, 'learning_rate': 0.15286628751533493, 'subsample': 0.5609995561293099, 'colsample_bytree': 0.9107839525851349, 'gamma': 4.4639142253717345, 'min_child_weight': 3, 'reg_alpha': 0.7024983253517825, 'reg_lambda': 4.402996978590108, 'max_bin': 441, 'scale_pos_weight': 5}. Best is trial 0 with value: 0.8483623591561059.
[I 2026-02-28 22:10:33,754] Trial 2 finished with value: 0.8849865108011669 and parameters: {'n_estimators': 460, 'max_depth': 7, 'learning_rate': 0.058288271065297985, 'subsample': 0.752208079685249, 'colsample_bytree': 0.9494296879055166, 'gamma': 0.07627332785264784, 'min_child_weight': 9, 'reg_alpha': 1.0468240672074374, 'reg_lambda': 2.2741982638321185, 'max_bin': 319, 'scale_pos_weight': 5}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:35,364] Trial 3 finished with value: 0.8291923940927385 and parameters: {'n_estimators': 481, 'max_depth': 18, 'learning_rate': 0.14373813925616655, 'subsample': 0.6458928768616983, 'colsample_bytree': 0.509712984241833, 'gamma': 4.124753125915293, 'min_child_weight': 10, 'reg_alpha': 4.406473481223967, 'reg_lambda': 4.209628676358889, 'max_bin': 353, 'scale_pos_weight': 2}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:36,685] Trial 4 finished with value: 0.840666080183882 and parameters: {'n_estimators': 347, 'max_depth': 21, 'learning_rate': 0.15211692448050174, 'subsample': 0.5098190958345095, 'colsample_bytree': 0.4057970484166593, 'gamma': 2.2828563859339357, 'min_child_weight': 7, 'reg_alpha': 3.6954197431219695, 'reg_lambda': 2.2172538403564683, 'max_bin': 308, 'scale_pos_weight': 2}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:37,905] Trial 5 finished with value: 0.8588455053565462 and parameters: {'n_estimators': 328, 'max_depth': 28, 'learning_rate': 0.05453902215050119, 'subsample': 0.6872820581631962, 'colsample_bytree': 0.8229179399394333, 'gamma': 1.672738963795632, 'min_child_weight': 2, 'reg_alpha': 0.12434714535378866, 'reg_lambda': 4.454720621991838, 'max_bin': 424, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:39,729] Trial 6 finished with value: 0.8807184498077083 and parameters: {'n_estimators': 447, 'max_depth': 23, 'learning_rate': 0.1937344316457743, 'subsample': 0.8729541072488274, 'colsample_bytree': 0.5439525395443389, 'gamma': 0.06516104716651372, 'min_child_weight': 2, 'reg_alpha': 1.3625009479969985, 'reg_lambda': 0.18293504922278492, 'max_bin': 379, 'scale_pos_weight': 5}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:40,608] Trial 7 finished with value: 0.832096152639496 and parameters: {'n_estimators': 114, 'max_depth': 9, 'learning_rate': 0.052995450923571524, 'subsample': 0.5725469794885734, 'colsample_bytree': 0.8763230763133465, 'gamma': 4.3949594897705655, 'min_child_weight': 2, 'reg_alpha': 1.7150617601590012, 'reg_lambda': 4.712967713741087, 'max_bin': 365, 'scale_pos_weight': 5}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:41,655] Trial 8 finished with value: 0.8357071094476304 and parameters: {'n_estimators': 211, 'max_depth': 14, 'learning_rate': 0.18523900816553743, 'subsample': 0.6317287734983809, 'colsample_bytree': 0.5777614803049199, 'gamma': 4.4576732083099095, 'min_child_weight': 5, 'reg_alpha': 1.5490580287582967, 'reg_lambda': 3.9378522220800116, 'max_bin': 444, 'scale_pos_weight': 2}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:42,453] Trial 9 finished with value: 0.8577502080991536 and parameters: {'n_estimators': 125, 'max_depth': 9, 'learning_rate': 0.15032435471081806, 'subsample': 0.8839446180948706, 'colsample_bytree': 0.5653411436341875, 'gamma': 1.8050415718161528, 'min_child_weight': 9, 'reg_alpha': 0.26455574317527986, 'reg_lambda': 1.259882021993743, 'max_bin': 361, 'scale_pos_weight': 4}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:44,288] Trial 10 finished with value: 0.8735839277859647 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.02927246031352468, 'subsample': 0.9800078575670169, 'colsample_bytree': 0.7239990036581708, 'gamma': 0.04839376347770377, 'min_child_weight': 7, 'reg_alpha': 2.9186429133733007, 'reg_lambda': 2.6878605882064, 'max_bin': 280, 'scale_pos_weight': 4}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:45,824] Trial 11 finished with value: 0.8754232072732492 and parameters: {'n_estimators': 492, 'max_depth': 27, 'learning_rate': 0.10613796521854764, 'subsample': 0.8443302241265834, 'colsample_bytree': 0.7238343091983178, 'gamma': 0.2780700672171688, 'min_child_weight': 5, 'reg_alpha': 1.4242034455730257, 'reg_lambda': 0.11315535867551896, 'max_bin': 510, 'scale_pos_weight': 4}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:46,966] Trial 12 finished with value: 0.8573254590228189 and parameters: {'n_estimators': 415, 'max_depth': 3, 'learning_rate': 0.19981326084863774, 'subsample': 0.8315054741511985, 'colsample_bytree': 0.37786481972778474, 'gamma': 0.7111322542788502, 'min_child_weight': 7, 'reg_alpha': 2.302490539292147, 'reg_lambda': 0.10667390021512335, 'max_bin': 321, 'scale_pos_weight': 5}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:48,529] Trial 13 finished with value: 0.8649585913143454 and parameters: {'n_estimators': 424, 'max_depth': 25, 'learning_rate': 0.1002187095624051, 'subsample': 0.7711539278307533, 'colsample_bytree': 0.6981826827343496, 'gamma': 0.9094702275153339, 'min_child_weight': 1, 'reg_alpha': 1.051051228097542, 'reg_lambda': 1.1730724968989679, 'max_bin': 265, 'scale_pos_weight': 3}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:50,036] Trial 14 finished with value: 0.8463186161571821 and parameters: {'n_estimators': 446, 'max_depth': 14, 'learning_rate': 0.030277382390173496, 'subsample': 0.9353071688136803, 'colsample_bytree': 0.9989712032683223, 'gamma': 3.3020450921524582, 'min_child_weight': 9, 'reg_alpha': 2.4111903470151903, 'reg_lambda': 1.1564892895076473, 'max_bin': 321, 'scale_pos_weight': 5}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:51,354] Trial 15 finished with value: 0.8582865549288632 and parameters: {'n_estimators': 368, 'max_depth': 9, 'learning_rate': 0.11617201633140195, 'subsample': 0.7678667405094535, 'colsample_bytree': 0.4750963998124227, 'gamma': 1.0975875212816621, 'min_child_weight': 4, 'reg_alpha': 0.9029620750858753, 'reg_lambda': 1.8670958209306714, 'max_bin': 407, 'scale_pos_weight': 4}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:52,857] Trial 16 finished with value: 0.8370537653881526 and parameters: {'n_estimators': 292, 'max_depth': 24, 'learning_rate': 0.07241909283009917, 'subsample': 0.8980706799938419, 'colsample_bytree': 0.30779321090512995, 'gamma': 3.146510252830694, 'min_child_weight': 8, 'reg_alpha': 3.0270954531268717, 'reg_lambda': 3.1670557711373046, 'max_bin': 298, 'scale_pos_weight': 3}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:54,339] Trial 17 finished with value: 0.8666956380154801 and parameters: {'n_estimators': 461, 'max_depth': 13, 'learning_rate': 0.12510942970465322, 'subsample': 0.8272170123658558, 'colsample_bytree': 0.6220713433174665, 'gamma': 0.4867449772323981, 'min_child_weight': 6, 'reg_alpha': 1.9192670498165045, 'reg_lambda': 3.538089062271294, 'max_bin': 493, 'scale_pos_weight': 3}. Best is trial 2 with value: 0.8849865108011669.
[I 2026-02-28 22:10:57,166] Trial 18 finished with value: 0.889029628756987 and parameters: {'n_estimators': 383, 'max_depth': 6, 'learning_rate': 0.015715457982575953, 'subsample': 0.7262874024338117, 'colsample_bytree': 0.7936674445528257, 'gamma': 0.0075107883045661405, 'min_child_weight': 10, 'reg_alpha': 0.5130622233081216, 'reg_lambda': 1.7256037555496369, 'max_bin': 343, 'scale_pos_weight': 5}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:10:58,940] Trial 19 finished with value: 0.8621192669625108 and parameters: {'n_estimators': 371, 'max_depth': 6, 'learning_rate': 0.01775281856926074, 'subsample': 0.7071071554641194, 'colsample_bytree': 0.8287184078541235, 'gamma': 1.2726418289387063, 'min_child_weight': 10, 'reg_alpha': 0.5464064278905917, 'reg_lambda': 1.8210649292846912, 'max_bin': 338, 'scale_pos_weight': 4}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:00,711] Trial 20 finished with value: 0.8512289958129985 and parameters: {'n_estimators': 290, 'max_depth': 6, 'learning_rate': 0.011947708929443981, 'subsample': 0.7321911059960489, 'colsample_bytree': 0.8165981776393502, 'gamma': 2.449277764222413, 'min_child_weight': 9, 'reg_alpha': 0.23451579754402418, 'reg_lambda': 0.7004295392744915, 'max_bin': 334, 'scale_pos_weight': 5}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:02,992] Trial 21 finished with value: 0.8887474615246583 and parameters: {'n_estimators': 394, 'max_depth': 11, 'learning_rate': 0.048753772782800756, 'subsample': 0.7925797678749417, 'colsample_bytree': 0.7732644213701112, 'gamma': 0.03577627447018199, 'min_child_weight': 10, 'reg_alpha': 1.1638083012634888, 'reg_lambda': 2.267341951349817, 'max_bin': 381, 'scale_pos_weight': 5}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:04,526] Trial 22 finished with value: 0.8685248945544298 and parameters: {'n_estimators': 381, 'max_depth': 6, 'learning_rate': 0.04799391067924612, 'subsample': 0.7888921862534398, 'colsample_bytree': 0.9934078166060344, 'gamma': 0.6215945941619755, 'min_child_weight': 10, 'reg_alpha': 1.0652675712383672, 'reg_lambda': 2.1497755884593013, 'max_bin': 291, 'scale_pos_weight': 5}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:06,811] Trial 23 finished with value: 0.8873679919925991 and parameters: {'n_estimators': 319, 'max_depth': 11, 'learning_rate': 0.07501448589001783, 'subsample': 0.6753026845159055, 'colsample_bytree': 0.7523314296306758, 'gamma': 0.008542931897130068, 'min_child_weight': 8, 'reg_alpha': 2.0996353507791436, 'reg_lambda': 2.4030028126418213, 'max_bin': 389, 'scale_pos_weight': 4}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:08,122] Trial 24 finished with value: 0.8654427314270714 and parameters: {'n_estimators': 319, 'max_depth': 12, 'learning_rate': 0.035164569163295634, 'subsample': 0.6559600973188491, 'colsample_bytree': 0.7772925798677444, 'gamma': 0.5341735763891662, 'min_child_weight': 8, 'reg_alpha': 1.9877413184500936, 'reg_lambda': 1.460253340064773, 'max_bin': 388, 'scale_pos_weight': 4}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:09,123] Trial 25 finished with value: 0.8556378590576289 and parameters: {'n_estimators': 256, 'max_depth': 11, 'learning_rate': 0.07924059525376143, 'subsample': 0.6970133390407863, 'colsample_bytree': 0.6605526207446059, 'gamma': 1.2094260405164492, 'min_child_weight': 8, 'reg_alpha': 2.957506258331487, 'reg_lambda': 3.18445640423278, 'max_bin': 418, 'scale_pos_weight': 4}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:10,453] Trial 26 finished with value: 0.8677961989093351 and parameters: {'n_estimators': 334, 'max_depth': 16, 'learning_rate': 0.06533144874357875, 'subsample': 0.6059915543262706, 'colsample_bytree': 0.7711215573196549, 'gamma': 0.3796108302359743, 'min_child_weight': 10, 'reg_alpha': 2.10548863370647, 'reg_lambda': 2.6277516605851186, 'max_bin': 464, 'scale_pos_weight': 4}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:11,513] Trial 27 finished with value: 0.8658137956243939 and parameters: {'n_estimators': 224, 'max_depth': 11, 'learning_rate': 0.0869481873125257, 'subsample': 0.8062046283005256, 'colsample_bytree': 0.6455674790301387, 'gamma': 0.8320825150295458, 'min_child_weight': 8, 'reg_alpha': 0.5308377031141472, 'reg_lambda': 1.6564581073255524, 'max_bin': 377, 'scale_pos_weight': 5}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:12,992] Trial 28 finished with value: 0.841546020857001 and parameters: {'n_estimators': 392, 'max_depth': 9, 'learning_rate': 0.043715941936746286, 'subsample': 0.6756925143020983, 'colsample_bytree': 0.7656017791242555, 'gamma': 3.228894189290566, 'min_child_weight': 9, 'reg_alpha': 3.5610777092063404, 'reg_lambda': 0.6814481118865372, 'max_bin': 346, 'scale_pos_weight': 4}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:14,225] Trial 29 finished with value: 0.8363242663064849 and parameters: {'n_estimators': 355, 'max_depth': 17, 'learning_rate': 0.09180725356466984, 'subsample': 0.73042694515867, 'colsample_bytree': 0.8924265855465057, 'gamma': 4.980397933396427, 'min_child_weight': 10, 'reg_alpha': 1.2803266987054798, 'reg_lambda': 2.791460459439688, 'max_bin': 398, 'scale_pos_weight': 3}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:15,407] Trial 30 finished with value: 0.8541320924792881 and parameters: {'n_estimators': 182, 'max_depth': 15, 'learning_rate': 0.020128945200657722, 'subsample': 0.7219760364947886, 'colsample_bytree': 0.690155304427074, 'gamma': 1.9036752063809925, 'min_child_weight': 6, 'reg_alpha': 0.0013948446127134417, 'reg_lambda': 3.0862972687495343, 'max_bin': 370, 'scale_pos_weight': 5}. Best is trial 18 with value: 0.889029628756987.
[I 2026-02-28 22:11:17,752] Trial 31 finished with value: 0.8900207361149229 and parameters: {'n_estimators': 422, 'max_depth': 7, 'learning_rate': 0.06759380499994472, 'subsample': 0.7518227556232588, 'colsample_bytree': 0.9566572156479658, 'gamma': 0.03209777621711737, 'min_child_weight': 9, 'reg_alpha': 0.6566007534282621, 'reg_lambda': 2.27815426444981, 'max_bin': 324, 'scale_pos_weight': 5}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:19,072] Trial 32 finished with value: 0.8744523883036927 and parameters: {'n_estimators': 407, 'max_depth': 4, 'learning_rate': 0.0709374379630143, 'subsample': 0.796490162291699, 'colsample_bytree': 0.856906067944177, 'gamma': 0.37037836936452984, 'min_child_weight': 9, 'reg_alpha': 0.6076663051136251, 'reg_lambda': 2.0514658740798106, 'max_bin': 399, 'scale_pos_weight': 5}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:20,987] Trial 33 finished with value: 0.8848100147661844 and parameters: {'n_estimators': 431, 'max_depth': 7, 'learning_rate': 0.040420989773451564, 'subsample': 0.7538991300122735, 'colsample_bytree': 0.9591924130975013, 'gamma': 0.07761975096939581, 'min_child_weight': 10, 'reg_alpha': 0.8171945126169916, 'reg_lambda': 2.4271259351841716, 'max_bin': 337, 'scale_pos_weight': 5}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:22,334] Trial 34 finished with value: 0.8593936126059927 and parameters: {'n_estimators': 389, 'max_depth': 11, 'learning_rate': 0.06451765429099565, 'subsample': 0.6153693421114782, 'colsample_bytree': 0.922582898390022, 'gamma': 1.4953017242231499, 'min_child_weight': 8, 'reg_alpha': 0.39401847105162, 'reg_lambda': 3.543748191065752, 'max_bin': 355, 'scale_pos_weight': 5}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:23,417] Trial 35 finished with value: 0.8614603717234328 and parameters: {'n_estimators': 266, 'max_depth': 8, 'learning_rate': 0.07833701875378618, 'subsample': 0.654103804300178, 'colsample_bytree': 0.7512277714525281, 'gamma': 0.9336054474744535, 'min_child_weight': 9, 'reg_alpha': 1.7643469083997863, 'reg_lambda': 2.4558986989183214, 'max_bin': 432, 'scale_pos_weight': 5}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:25,380] Trial 36 finished with value: 0.8707137167971355 and parameters: {'n_estimators': 318, 'max_depth': 5, 'learning_rate': 0.024609688268644583, 'subsample': 0.6781353760516486, 'colsample_bytree': 0.8183790152051457, 'gamma': 0.021937810688691252, 'min_child_weight': 10, 'reg_alpha': 4.847078074401179, 'reg_lambda': 1.6626315961514053, 'max_bin': 391, 'scale_pos_weight': 4}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:26,618] Trial 37 finished with value: 0.8677611533544247 and parameters: {'n_estimators': 353, 'max_depth': 19, 'learning_rate': 0.054755981294359296, 'subsample': 0.5875185242452395, 'colsample_bytree': 0.8546429103658704, 'gamma': 0.298887534411802, 'min_child_weight': 7, 'reg_alpha': 2.689716639084284, 'reg_lambda': 2.067482574631584, 'max_bin': 313, 'scale_pos_weight': 5}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:27,883] Trial 38 finished with value: 0.8598300267491336 and parameters: {'n_estimators': 451, 'max_depth': 10, 'learning_rate': 0.09393128520534083, 'subsample': 0.7429159786745125, 'colsample_bytree': 0.7916845653749518, 'gamma': 1.4717648290733718, 'min_child_weight': 9, 'reg_alpha': 1.069749447521375, 'reg_lambda': 2.35809015976295, 'max_bin': 410, 'scale_pos_weight': 1}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:29,498] Trial 39 finished with value: 0.8407386330122899 and parameters: {'n_estimators': 477, 'max_depth': 7, 'learning_rate': 0.011046856597000318, 'subsample': 0.5401911734100182, 'colsample_bytree': 0.9470842812189615, 'gamma': 3.6107764833319083, 'min_child_weight': 10, 'reg_alpha': 0.7908948428153159, 'reg_lambda': 0.8326909357790837, 'max_bin': 454, 'scale_pos_weight': 4}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:30,621] Trial 40 finished with value: 0.8548292253905594 and parameters: {'n_estimators': 341, 'max_depth': 12, 'learning_rate': 0.0629267655424666, 'subsample': 0.7089814517001294, 'colsample_bytree': 0.9006185635550399, 'gamma': 2.026202751226525, 'min_child_weight': 8, 'reg_alpha': 1.2507789118339727, 'reg_lambda': 2.8469578916999607, 'max_bin': 350, 'scale_pos_weight': 5}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:32,660] Trial 41 finished with value: 0.8876936323705863 and parameters: {'n_estimators': 472, 'max_depth': 5, 'learning_rate': 0.05495899752310139, 'subsample': 0.778542035677461, 'colsample_bytree': 0.9597594549855653, 'gamma': 0.01705752586719132, 'min_child_weight': 9, 'reg_alpha': 1.6397166186265244, 'reg_lambda': 2.2773885953772988, 'max_bin': 321, 'scale_pos_weight': 5}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:34,203] Trial 42 finished with value: 0.8743163688372713 and parameters: {'n_estimators': 474, 'max_depth': 5, 'learning_rate': 0.040247286117558165, 'subsample': 0.7768311352230103, 'colsample_bytree': 0.9544987506210075, 'gamma': 0.25805768366645465, 'min_child_weight': 9, 'reg_alpha': 1.6057637002223772, 'reg_lambda': 1.9078108404959595, 'max_bin': 327, 'scale_pos_weight': 5}. Best is trial 31 with value: 0.8900207361149229.
[I 2026-02-28 22:11:36,375] Trial 43 finished with value: 0.8864277722447167 and parameters: {'n_estimators': 498, 'max_depth': 8, 'learning_rate': 0.05023724560643151, 'subsample': 0.8174445945525624, 'colsample_bytree': 0.8650296302479088, 'gamma': 0.016516257237032428, 'min_child_weight': 9, 'reg_alpha': 2.193696672673209, 'reg_lambda': 2.257989174830566, 'max_bin': 309, 'scale_pos_weight': 5}. Best is trial 31 with value: 0.8900207361149229.

In [606]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.8944242869950975
Best hyperparameters: {'n_estimators': 396, 'max_depth': 6, 'learning_rate': 0.055646673462875905, 'subsample': 0.9242842749526948, 'colsample_bytree': 0.987149916017539, 'gamma': 0.005296845036153867, 'min_child_weight': 7, 'reg_alpha': 0.41682205567964414, 'reg_lambda': 2.289001953829556, 'max_bin': 322, 'scale_pos_weight': 5}

In [607]:
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# best_model from Optuna
model_xgb_optuna = XGBRegressor(**study.best_trial.params, random_state=42)

# Pipeline with preprocessor
pipeline_xgb_optuna = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', model_xgb_optuna)
])

# Fit the model to the training data
pipeline_xgb_optuna.fit(X_train, y_train)
    
y_pred_xgb_optuna = pipeline_xgb_optuna.predict(X_test)
    
y_pred_xgb_optuna = np.expm1(y_pred)
    
mae = mean_absolute_error(np.expm1(y_test), y_pred_xgb_optuna)
mse = mean_squared_error(np.expm1(y_test), y_pred_xgb_optuna)
r2 = r2_score(np.expm1(y_test), y_pred_xgb_optuna)

print(f"MAE: {mae:.4f}")
print(f"MSE: {mse:.4f}")
print(f"R²: {r2:.4f}")

MAE: 208479.3957
MSE: 15289993069907.3984
R²: -1989377792532.8020

In [608]:
mean_absolute_error(np.expm1(y_test),y_pred_xgb_optuna)

208479.3956511073

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'balcony',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['agePosse...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.1,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=5, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=None,
                              num_parallel_tree=None, ...))])

### Exporting the model

In [ ]:
# preprocessor = ColumnTransformer(
#     transformers=[
#         ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
#         ('cat', OrdinalEncoder(), columns_to_encode),
#         ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
#     ], 
#     remainder='passthrough'
# )

# pipeline = Pipeline([
#     ('preprocessor', preprocessor),
#     ('regressor', RandomForestRegressor(n_estimators=500))
# ])

# pipeline.fit(X,y_transformed)

In [613]:
# Best model
print(search_xgb.best_score_)
print(search_xgb.best_params_)

0.8953634094452262
{'regressor__colsample_bytree': 0.8, 'regressor__learning_rate': 0.1, 'regressor__max_depth': 5, 'regressor__n_estimators': 300}

In [612]:
search_xgb.best_estimator_

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'balcony',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['agePosse...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.1,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=5, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [614]:
import pickle

final_pipe = search_xgb.best_estimator_
with open('pipeline.pkl', 'wb') as file:
    # pickle.dump(pipeline, file)
    pickle.dump(final_pipe, file)

In [615]:
with open('df.pkl', 'wb') as file:
    pickle.dump(X, file)

In [616]:
X

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor
...,...,...,...,...,...,...,...,...,...,...,...,...
3549,flat,sector 84,2.0,2.0,1,Relatively New,532.0,0.0,0.0,unfurnished,Medium,Mid Floor
3550,house,sector 109,5.0,5.0,3+,Relatively New,6228.0,1.0,1.0,unfurnished,High,Low Floor
3551,flat,sector 2,1.0,1.0,1,Moderately Old,665.0,0.0,0.0,semifurnished,Medium,Mid Floor
3552,house,sector 43,5.0,6.0,3,Moderately Old,5490.0,1.0,1.0,unfurnished,Medium,Mid Floor
3553,flat,sector 68,3.0,3.0,3+,Relatively New,1845.0,0.0,0.0,semifurnished,Medium,High Floor

### Trying out the predictions

In [617]:
X.columns

Index(['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category'],
      dtype='str')

In [618]:
X.iloc[0].values

array(['flat', 'sector 36', np.float64(3.0), np.float64(2.0), '2',
       'New Property', np.float64(850.0), np.float64(0.0),
       np.float64(0.0), 'unfurnished', 'Low', 'Low Floor'], dtype=object)

In [710]:
data = [['flat', 'sector 38', 1, 5, '0', 'Relatively New', 1200, 0, 0, 'semifurnished', 'Medium', 'Mid Floor']]
# data = [['house', 'sector 38', 4, 3, '3+', 'New Property', 2750, 0, 0, 'unfurnished', 'Low', 'Low Floor']]
columns = ['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category']

# Convert to DataFrame
one_df = pd.DataFrame(data, columns=columns)

one_df

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 38,1,5,0,Relatively New,1200,0,0,semifurnished,Medium,Mid Floor

In [711]:
print(np.expm1(final_pipe.predict(one_df)))
print(round(np.expm1(final_pipe.predict(one_df)[0]), 2))

[2.6295035]
2.63

In [659]:
X.dtypes

property_type          str
sector                 str
bedRoom            float64
bathroom           float64
balcony                str
agePossession          str
built_up_area      float64
servant room       float64
store room         float64
furnishing_type     object
luxury_category        str
floor_category         str
dtype: object

In [623]:
sorted(X['sector'].unique().tolist())

['dwarka expressway',
 'gwal pahari',
 'manesar',
 'sector 1',
 'sector 10',
 'sector 102',
 'sector 103',
 'sector 104',
 'sector 105',
 'sector 106',
 'sector 107',
 'sector 108',
 'sector 109',
 'sector 11',
 'sector 110',
 'sector 111',
 'sector 112',
 'sector 113',
 'sector 12',
 'sector 13',
 'sector 14',
 'sector 15',
 'sector 17',
 'sector 2',
 'sector 21',
 'sector 22',
 'sector 23',
 'sector 24',
 'sector 25',
 'sector 26',
 'sector 27',
 'sector 28',
 'sector 3',
 'sector 30',
 'sector 31',
 'sector 33',
 'sector 36',
 'sector 37',
 'sector 37d',
 'sector 38',
 'sector 39',
 'sector 4',
 'sector 40',
 'sector 41',
 'sector 43',
 'sector 45',
 'sector 46',
 'sector 47',
 'sector 48',
 'sector 49',
 'sector 5',
 'sector 50',
 'sector 51',
 'sector 52',
 'sector 53',
 'sector 54',
 'sector 55',
 'sector 56',
 'sector 57',
 'sector 58',
 'sector 59',
 'sector 6',
 'sector 60',
 'sector 61',
 'sector 62',
 'sector 63',
 'sector 63a',
 'sector 65',
 'sector 66',
 'sector 67',
 'sector 67a',
 'sector 68',
 'sector 69',
 'sector 7',
 'sector 70',
 'sector 70a',
 'sector 71',
 'sector 72',
 'sector 73',
 'sector 74',
 'sector 76',
 'sector 77',
 'sector 78',
 'sector 79',
 'sector 8',
 'sector 80',
 'sector 81',
 'sector 82',
 'sector 82a',
 'sector 83',
 'sector 84',
 'sector 85',
 'sector 86',
 'sector 88',
 'sector 88a',
 'sector 89',
 'sector 9',
 'sector 90',
 'sector 91',
 'sector 92',
 'sector 93',
 'sector 95',
 'sector 99',
 'sohna road']